### ISSUE TITLE
Pry and Fuubar

### ISSUE THREAD

**Issue by Nerian** [thekompanee/fuubar#100]
Hi,

I think this commit introduced a change that makes Fuubar incompatible with Pry:

https://github.com/thekompanee/fuubar/commit/4433b97ac28b4d201ab53f5ac15263123dc384a5

When running the spec, having a `binding.pry` will stop the execution at that point. But the progress bar keeps overwriting the ruby console. I think the reason may be the comment I mentioned.

I am using fuubar (2.3.0)

**Comment by jfelchner** [comment]
Thanks for the report @Nerian!  I'm looking into it!

**Comment by jfelchner** [comment]
@Nerian this should be fixed in `2.3.1`.  Give it a try and let me know if there are issues.

**Comment by Nerian** [comment]
All fixed. Thanks!

**Comment by elkesrio** [comment]
The problem appeared again. I'm using the `2.4.0` version
