### ISSUE TITLE
Show skipped tests

### ISSUE THREAD

**Issue by BattleBrisket** [thekompanee/fuubar#104]
## Current Problem
I have a large test suite that has several incomplete tests. Fuubar hides RSpec's default "skipped test" output, leaving me to dig through code to find them (edit: or turn off fuubar and rerun the suite, enabling default rspec output).

## Potential Solution or New Behavior
I'd like a command line and/or config option to output the skipped tests.

### Mockups
In `spec_helper.rb`
```
config.fuubar.show_skipped = true;
# or
Fuubar.show_skipped = true;
```

Then in test results:
```
 329/329 |=================== 100 ===================>| Time: 00:02:24
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) an example is skipped
     # No reason given
     # ./skipped_spec.rb:2
```

**Comment by jfelchner** [comment]
@BattleBrisket not sure what you mean here.  I just ran Fuubar with a skipped spec:

```ruby
skip 'it is skipped' do
  expect(1).to be 1
end
```

and received:

```
 1/1 |=============== 100 ==============>| Time: 00:00:10

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Project::Thing it is skipped
     # No reason given
     # ./spec/models/project/thing_spec.rb:18


Finished in 10.87 seconds (files took 2.93 seconds to load)
1 example, 0 failures, 1 pending
```

So I'm not sure what more information you'd like.

**Comment by jfelchner** [comment]
Feel free to ping me back here and I'll reopen this if necessary.
