### ISSUE TITLE
Byebug incompatibility

### ISSUE THREAD

**Issue by runephilosof** [thekompanee/fuubar#105]
## Current Behavior
Sometimes fuubar output is included in the byebug output.

### Steps to Reproduce
1. Add gem 'byebug' and gem 'fuubar' to a rails project.
2. add byebug to some application code that has test coverage
3. run the test
4. call method or local variable name and repeat it.

### Screenshot
![fuubar-byebug-bug](https://user-images.githubusercontent.com/948625/45736862-84d49380-bbec-11e8-9509-7fea3a7ca78e.png)
![fuubar-byebug-bug-2](https://user-images.githubusercontent.com/948625/45737040-117f5180-bbed-11e8-9072-59e35e2a644e.png)

## Expected Behavior
When byebug is halting the test no output from fuubar should show.

## Environment

 - OS:

    - [ ] Windows
    - [ ] macOS
    - [ ] iOS
    - [ ] Android
    - [X] Linux
    - [ ] Other

 - OS Version: A docker environment built on ubuntu:14.04

**Comment by shime** [comment]
Same happens with pry, would be nice to be able to disable the progress output while debugging with pry.

**Comment by hoblin** [comment]
That's really easy to disable. Just run `rspec spec/some_file_spec.rb --format documentation` when you need debugger. That will override `--format` option in `.rspec` file for this run.

**Comment by k-rudy** [comment]
any plans to fix this one? Very annoying issue

**Comment by jfelchner** [comment]
Sorry about this everyone.  This slipped by me.  So effectively what's happening here is that we added the ability for the bar to automatically refresh things like ETA when in the middle of a long-running task.

The side effect of this is that, apparently, when we're in the middle of a byebug session, it continues refreshing the bar.

Let me see what I can do here.

**Comment by jfelchner** [comment]
@shime pry should be working fine however.  We already [check for Pry](https://github.com/thekompanee/fuubar/blob/master/lib/fuubar.rb#L56-L63) and disable the auto-refresh automatically.

**Comment by jfelchner** [comment]
This new option is as good as I can get considering I can't seem to find a way to auto-disable when byebug is entered into.  Hope this is good enough!
