### ISSUE TITLE
Fuubar not compatible with Rspec 3.8

### ISSUE THREAD

**Issue by ethan-dowler** [thekompanee/fuubar#106]
## Current Problem
Fuubar has an rspec dependency of "~> 3.7"

I recently tried to update rspec in my project to 3.8, and i could not do it without removing the fuubar gem.

I like the fuubar gem, so I would like to see it support rspec 3.8.

## Potential Solution
Remove rspec 3.7 restriction

### Mockups
```
# in fuubar.gemspec
spec.add_development_dependency 'rspec',            ["~> 3.8"]
```

**Comment by jfelchner** [comment]
@ethan-dowler that's only for a development dependency, which doesn't affect users of the gem.  Even still both that dependency and the `rspec-core` dependency is pessimistic.  Which means it'll work until RSpec `4.0`.

Something else must be going on in your Gemfile.

**Comment by jfelchner** [comment]
Odds are you didn't properly `bundle update` which told you there was a conflict when there really wasn't.  It's a common issue.

**Comment by ethan-dowler** [comment]
ha. probably. one of my other apps updated fine. I'll double check everything. Thanks.
