### ISSUE TITLE
Gem fails to bundle, unitilized constant in .gemspec

### ISSUE THREAD

**Issue by donquxiote** [thekompanee/fuubar#110]
## Current Behavior
latest version of fuubar throws an uninitialized constant error when either running `bundle install` within the gem directory or when included in a gemfile.

```bash
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `fuubar.gemspec`: uninitialized constant Fuubar. Bundler cannot continue.

 #  from /Users/james.buckley/dev/test/fuubar/fuubar.gemspec:25
 #  -------------------------------------------
 #      'changelog_uri'     => 'https://github.com/thekompanee/fuubar/blob/master/CHANGELOG.md',
 >      'documentation_uri' => "https://github.com/thekompanee/fuubar/tree/releases/v#{Fuubar::VERSION}",
 #      'homepage_uri'      => 'https://github.com/thekompanee/fuubar',
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /Users/james.buckley/dev/test/fuubar/Gemfile:10
 #  -------------------------------------------
 #  # Specify your gem's dependencies in fuubar.gemspec
 >  gemspec
 #  -------------------------------------------
```

If I remove the call to `Fuubar::Version` I get another error;

```bash
The gemspec at /Users/james.buckley/dev/test/fuubar/fuubar.gemspec is not valid. Please fix this gemspec.
The validation error was 'metadata values must be a String'
```
Which appears to come from this line: `fuubar.gemspec:22`:
```bash
'allowed_push_host' => nil,
```

### Steps to Reproduce
1. check out gem 
2. run `bundle install` from within that directory

OR

1. add gem to your gemfile
2. run `bundle install` for your project 

## Expected Behavior
I'd expect that the gem would build correctly.

## Environment

 - Device: Macbook Pro
 - Bundler: tried with Bundler version 1.16.2, and 1.17.2
 - OS:

    - [ ] Windows
    - [X] macOS
    - [ ] iOS
    - [ ] Android
    - [ ] Linux
    - [ ] Other

 - OS Version: 10.14.5

**Comment by jfelchner** [comment]
@donquxiote I find it odd that you're getting this error and no one else is.

**Comment by donquxiote** [comment]
that's fair! I'll try it on a separate machine later this week, it could be an environmental thing. I wanted to document it as I found it though. I'm guessing you have metrics showing folks are using the latest version? I had imagined a possibility (incredibly slim though,) that the last version was locked in by `Gemfile.lock` files so no one got the update

**Comment by jfelchner** [comment]
@donquxiote I'm super curious where that's even coming from because that isn't even remotely what the current gemspec looks like.

https://github.com/thekompanee/fuubar/blob/master/fuubar.gemspec

**Comment by jfelchner** [comment]
@donquxiote releasing a new version now and yanking `2.4.0`.  Just in case anyone else is running into this.  Better safe than sorry.  I'll reopen if `2.4.1` doesn't fix it for ya.

**Comment by donquxiote** [comment]
Sorry about the unnecessary issue. It looks like when I was trying to merge in the latest to my fork I overwrote or lost some changes on the gemspec file. That's how I got those weird lines that didn't exist in the master branch. My mistake was assuming that my merge had gone cleanly and the master branches were the same between forks without checking. Thanks for the quick replies though!

**Comment by jfelchner** [comment]
@donquxiote ugh.  That sucks.  I yanked the 2.4.0 version of the gem and made a lot of people very unhappy.  I won't be doing that again in the future.  :/
