### ISSUE TITLE
2.4.0 gem yanked

### ISSUE THREAD

**Issue by bpo** [thekompanee/fuubar#111]
Version 2.4.0 is the latest gem in the [changelog](https://github.com/thekompanee/fuubar/blob/master/CHANGELOG.md), but is no longer available for download due to a [yank from rubygems](https://rubygems.org/gems/fuubar/versions/2.4.0).

Why was this version yanked? Any chance this could be explained with a note about what's new in 2.4.1 in the changelog?

**Comment by jfelchner** [comment]
@bpo there was an error in the gemspec which was causing people's builds to fail with certain `Gemfile` configurations.  See issue #110 

A `bundle update` should be all you need to do.

**Comment by denschub** [comment]
For future incidents, could you please *not* yank versions that have been released for a month?

The yank broke diaspora out of the blue, and potentially a lot of other projects, and 2.4.0 was working just fine in our case (and looking at #110, it was probably fine for most people).

**Comment by jfelchner** [comment]
@denschub In hindsight, I wouldn't do that again in this particular case when most people weren't having an issue with it.

**Comment by denschub** [comment]
❤️
