### ISSUE TITLE
For version 2.4.1 strange behavior for 'binding.pry' in spec. Version 2.3.2 is OK.

### ISSUE THREAD

**Issue by foton** [thekompanee/fuubar#112]
## Current Behavior

When I use  `binding.pry` in feature spec, run is stopped, but I cannot use console. Not happened in 2.3.2.

### Steps to Reproduce

1. Set breakpoint `binding.pry` in `some_file_spec.rb`
2. Run `bundle exec rspec spec/..../some_file_spec.rb`
3. When execution stops, try to write some command. Progress bar is periodically intercept writen commands. It seems, that it reacts on keypress with small delay (aprox 1second) .

### Screenshot

With 2.3.2
![Snímek z 2019-07-18 17-13-07](https://user-images.githubusercontent.com/483873/61469499-978c3600-a97f-11e9-8466-610627cd67b7.png)

After update to 2.4.1
![Snímek z 2019-07-18 17-14-53](https://user-images.githubusercontent.com/483873/61469728-02d60800-a980-11e9-9ade-52485c56ef06.png)

## Environment

 - Device: Notebook

 - OS:

    - [ ] Windows
    - [ ] macOS
    - [ ] iOS
    - [ ] Android
    - [x] Linux
    - [ ] Other

 - OS Version: Ubuntu 18.04.2 LTS

 - Browser:

    - [ ] Chrome
    - [ ] Safari
    - [ ] Firefox
    - [ ] Internet Explorer
    - [ ] Edge
    - [ ] Opera

 - Browser Version:

**Comment by jfelchner** [comment]
@foton so sorry about this mate.  It turns out that we moved some code around that I didn't think would affect this, but it turns out that it did.  I'm going to be removing all Pry support from `fuubar` in the next release and the auto-refresh functionality will be opt-in.  See #109 for more details.
