### ISSUE TITLE
RSpec output creates multiple new lines

### ISSUE THREAD

**Issue by safetypins** [thekompanee/fuubar#118]
Current Behavior
--------------------------------------------------------------------------------

  1. Add the fuubar gem, `bundle install`
  2. Add configuration to `spec_helper.rb`
  3. Run tests

### Screenshot

![Screen Shot 2021-05-07 at 11 06 41 AM](https://user-images.githubusercontent.com/111799/117478417-baa52280-af24-11eb-9a27-9345f36cad74.png)

Expected Behavior
--------------------------------------------------------------------------------
Expect to see progress output on a single line that is updated

Environment
--------------------------------------------------------------------------------

  * Device: 2017 MacBook Pro

  * OS: 

    * [ ] Windows
    * [x] macOS
    * [ ] iOS
    * [ ] Android
    * [ ] Linux
    * [ ] Other

  * OS Version: 10.15
  * Shell: Zsh, managed by Oh My ZSH!

**Comment by safetypins** [comment]
I wondered that it could have something to do with the shell or the way I have my prompt formatted. I switched to bash and ran guard again, and got the same results.

**Comment by jfelchner** [comment]
@safetypins you are running RSpec with Fuubar as well as the default formatter.  Run it with only Fuubar and it will be fine.
