### ISSUE TITLE
Use fuubar together with parallel-test?

### ISSUE THREAD

**Issue by jensb** [thekompanee/fuubar#22]
Hello,

I am using the parallel-tests gem which REALLY REALLY speeds up test time (since we have an 8-core machine to develop on ...). However, looking at the spec results is a mess, since they just get spit out to the console.

Would you be interested in collaborating getting fuubar running with parallel-tests so that you get one progress bar per process, and the failing tests are output cleanly to the console?

Thanks!
Jens

**Comment by mattpickle** [comment]
+1

**Comment by jfelchner** [comment]
Hey all, I don't want to come across as a jerk, but I don't use Parallel Tests. I understand it's usefulness though. So as I said before, I'll gladly accept a PR.

So you can +1 this issue all you want but it's not going to change the fact that it's not getting done without a PR.

**Comment by thedrow** [comment]
@jfelchner Any idea what needs to be done?

**Comment by jfelchner** [comment]
@thedrow no clue.

**Comment by Karolis-Sakavicius** [comment]
+1

**Comment by rgaufman** [comment]
Any solution to this in 2020? :)
