### ISSUE TITLE
Progress bar update prints on new line

### ISSUE THREAD

**Issue by whargrove** [thekompanee/fuubar#53]
I installed Fuubar and updated .rspec per the readme, but each update prints on a new line when executing rspec.

![screen shot 2014-01-02 at 8 27 59 pm](https://f.cloud.github.com/assets/1852758/1837447/6bd5d6dc-742f-11e3-8312-820c593aab2f.png)

Any ideas?

**Comment by excalq** [comment]
I've had the same thing happen, but it turned out to be due to a misformatted .rspec file, in which I had commented out old formats, as well as having an explanation comment after the --format line. Removing these fixed it.

```
#--format documentation
--format Fuubar ## This is better for our project with long test times
--color
```
