### ISSUE TITLE
No progress output in circleci

### ISSUE THREAD

**Issue by p-run** [thekompanee/fuubar#75]
In CircleCI when using fuubar we are not getting any progress output. We get the failure reports as soon as a test fails, and the output appears at the end of the test run, but while tests are running there is no feedback as to where in the process they are (or if they are actually progressing at all).

**Comment by jfelchner** [comment]
@p-run I'm definitely seeing this too.  Can you try setting the `CONTINUOUS_INTEGRATION` environment variable to `true` in your `circle.yml`?  See if that affects anything.

Also, they way things are output on Travis and Circle cannot be the same as they are in terminal.  There are limitations.  You're not actually seeing terminal output, you're seeing the output of a stream being rendered realtime.

`ruby-progressbar` overrides whatever format you've specified in those situations so even if it displays, it won't look like what it looks like in your terminal.  See [here](https://github.com/jfelchner/ruby-progressbar/wiki/Non-TTY-Output).

**Comment by p-run** [comment]
I understand the difference between tty/notty output, static bars are actually a great solution (I would have accepted one dot per test).

Will try CONTINUOUS_INTEGRATION as soon as I can, thanks.

**Comment by jfelchner** [comment]
@p-run I just tried it and adding:

```yml
machine:
  environment:
    CONTINUOUS_INTEGRATION: true
```

And it works.

**Comment by p-run** [comment]
Verified, I am getting a fancy progressbar now, thanks!

**Comment by nihtalak** [comment]
It reproduces on Travis CI. I have tried: 
```yaml
env:
  global:
    - CONTINUOUS_INTEGRATION=true
```
didn't work.
