### ISSUE TITLE
Fix for "irb: warn: can't alias context from irb_context." error

### ISSUE THREAD

**Issue by willkoehler** [thekompanee/fuubar#78]
When I use fuubar in a Rails project by including fuubar in my Gemfile:
```ruby
gem 'fuubar'
```
I get a warning "irb: warn: can't alias context from irb_context." when I run `bundle exec rails c`
```bash
Sapphire:cms will$ bundle exec rails c
Loading development environment (Rails 4.2.1)
irb: warn: can't alias context from irb_context.
irb(main):001:0>
```
I believe this started after upgrading to RSpec 3. It's similar to this issue in PaperTrail https://github.com/airblade/paper_trail/issues/381

This could be fixed by removing the first line:
```ruby
require 'rspec'
```
from `fuubar.rb`

A work-around until this fix is applied is to change the fuubar gem line to
```ruby
gem 'fuubar', :require => false
```
I just realized this can also be fixed by putting the fuubar gem line in the test group
```ruby
group :test do
  gem 'fuubar'
end
```

**Comment by jfelchner** [comment]
Which is where it should be :) Glad you got it straight!
