### ISSUE TITLE
Add ruby 2.2.4 support to circle

### ISSUE THREAD

**Issue by markburns** [thekompanee/fuubar#85]
Glancing at the `.circle.yml` file, it looks like there is no mention of ruby versions in there.
Presumably you set that up in the web UI?

Would you mind adding ruby 2.2.4?

Alternatively, I could do a PR for adding this to the yml?

**Comment by jfelchner** [comment]
@markburns I'll take a look. Thanks!

**Comment by jfelchner** [comment]
@markburns switched back to Travis and have a latest Ruby 2.2 build going just for you now. :)

**Comment by markburns** [comment]
Thanks! That satisfies a client's qualm about using this gem, but funnily enough we are now on ruby 2.3.0. 

I won't trouble you with asking to add that too, as personally I can't imagine what you might be doing that could break across those versions. In fact I'd be impressed to see well intentioned code that does

**Comment by jfelchner** [comment]
@markburns already added 2.3 the same time I added 2.2 ;)

**Comment by markburns** [comment]
Ok great stuff, thanks! BTW you have no idea how much easier this gem is
currently making my life.
Thanks again.

**Comment by jfelchner** [comment]
@markburns if your client is worried about security, take a look at [this](https://github.com/jfelchner/ruby-progressbar/wiki/Installation#gem-signing) and [this](https://github.com/thekompanee/fuubar/blob/b749d84788bdb88881c16adcc018174282780070/README.md#security) :wink:
