### ISSUE TITLE
irb: warn: can't alias context from irb_context.

### ISSUE THREAD

**Issue by joelmichael** [thekompanee/fuubar#93]
I am getting this error again on version 2.2.0. `require: false` does not fix it. I ended up moving fuubar into the test group.

See #78

**Comment by jfelchner** [comment]
Although it'd be nice to figure out where this is happening (and if there's anything we can do in `fuubar` to fix it, I believe that moving it into the test group is on ok fix for this and I'm probably not going to spend time to dive into it.

@joelmichael can you confirm that `2.1` does _not_ do this but `2.2` does?

**Comment by joelmichael** [comment]
The problem was actually caused by rspec 3.5.0, which was enabled by fuubar changing its dependency from rspec to rspec-core. I'm not entirely sure why that allowed rspec to update, but... anyway I don't think it's your fault. I think I was confused to think fuubar was related because it was affected in a prior issue... closing this.

**Comment by jfelchner** [comment]
👍🏻
