### ISSUE TITLE
Gitlab CI strange output

### ISSUE THREAD

**Issue by ivanovaleksey** [thekompanee/fuubar#98]
Hi, thanks for the nice gem!

I don't think it is a issue with the gem really but I don't where to start my investigations.
I use the gem on Gitlab CI.

So I run RSpec with a command `bundle exec rspec --format Fuubar`.
But it gives me very poor progress bar formatting. 

As I can see I should somehow force `tty` option. I found [this](https://github.com/thekompanee/fuubar/pull/88) PR, added `--tty` option to my initial command.

And now the output looks like the following:
![image](https://cloud.githubusercontent.com/assets/11523473/23026516/8ffdc09e-f472-11e6-8df9-74692bbbddb3.png)

I don't quite understand what causes the issue. Is it something with Gitlab CI settings?
Is there anything I can do to avoid this behaviour? 
I would like progress bar to be rewritten on the same line (as it works locally).

Thanks.

**Comment by jfelchner** [comment]
@ivanovaleksey you actually want the opposite.  Remove the `--tty` option and instead set the `CONTINUOUS_INTEGRATION` environment variable to `true` in your build.  That should solve your problem.

**Comment by ivanovaleksey** [comment]
Thank you for the reply @jfelchner.
With `CONTINUOUS_INTEGRATION=true bundle exec rspec --format Fuubar` command progress bar looks like this (as it described in progress bar wiki [page](https://github.com/jfelchner/ruby-progressbar/wiki/Non-TTY-Output)): 
```
Progress: |===================
```

Is there any way to get progress bar with `' %c/%C |%w>%i| %e '` format but on the same line?

**Comment by jfelchner** [comment]
@ivanovaleksey not unless Gitlab starts supporting ANSI codes and carriage returns in their log output.

**Comment by ivanovaleksey** [comment]
Thank you @jfelchner for the explanation.
