### ISSUE TITLE
Inline images 

### ISSUE THREAD

**Issue by cmitz** [thekompanee/fuubar#99]
So, I was working on failing feature specs. The problem consisted of some timing issues. In the process, I decided to implement `capybara-inline-screenshot`. However, I couldn't figure out why the screenshots would only pop-up in Buildkite (CI) and not locally. Now it looks like Fuubar was toying with me ;-)

Any idea why this issue exists only when working with Fuubar?

### Expected behaviour

_Context: pretty vanilla Rails setup with Capybara and PhantomJS for feature specs._

After failing, I expected `capybara-inline-screenshot` to output something that looks like an image in iTerm. Normally (with ` rspec --format progress` the [image is right after the filename](https://github.com/buildkite/capybara-inline-screenshot/blob/master/lib/capybara-inline-screenshot/rspec.rb#L16).

### Actual

This is all I get.

```
2/2 |============================================= 100 ==============================================>| Time: 00:00:15
  HTML screenshot: file:///Users/user/src/project/tmp/capybara/screenshot_2017-08-16-13-36-47.879.html
  Image screenshot: file:///Users/user/src/project/tmp/capybara/screenshot_2017-08-16-13-36-47.879.png

Top 2 slowest examples (7.17 seconds, 46.7% of total time):
```

**Comment by jfelchner** [comment]
@cmitz I'm not familiar with this gem.  I'm happy to put a patch in if it's not something too crazy.  Unfortunately the `output` variable which is specified in that link you added is not referenced in that module so I'm not sure where it's coming from.

As far as `fuubar` is concerned, it doesn't do anything with output at all except for wrap whatever output variable RSpec is using (which is what I would assume is also what that gem does that you added.

My guess is that [these lines](https://github.com/buildkite/capybara-inline-screenshot/blob/master/lib/capybara-inline-screenshot/rspec.rb#L21-L22), which don't specify the Fuubar class might be what is causing the issue.

Again, if you can give me a reproducible test case, and more information on what's happening, I'd be happy to look at it.
